### PR TITLE
Add missing prefix_subject function

### PR DESCRIPTION
**Pull request by hooopo**

### CODE REVIEW

**Comment by vipulnsward** [comment]
Thanks @hooopo. 
This was removed as part of https://github.com/bigbinary/mail_interceptor/commit/3c6e9689e78a8edbf589d284b03a0146af421847

@neerajdotname was that intentional, or we removed the ENV info prefix as a mistake.

**Comment by neerajdotname** [comment]
Yes that was intentional. It's not that simple. There is a lot of code.

We use https://github.com/wireframe/email_prefixer .

@hooopo  Please let us know if https://github.com/wireframe/email_prefixer will solve your problem. 

We will add it to our README so that others can use https://github.com/wireframe/email_prefixer too.

**Comment by hooopo** [comment]
@neerajdotname @vipulnsward 

Yes, add email prefixer info to README is useful, and you'd better remove old subject_prefix info ^_^
> Besides method intercept? method name is needed if you have provided subject_prefix. This name will be appended to the subject_prefix to produce something like [WHEEL STAGING] Forgot password. In this case STAGING came form name.

While still do not know what's wrong with this PR, even though it works fine in my App, however `email prefixer` is awesome. Thanks a lot.

**Comment by neerajdotname** [comment]
PR https://github.com/bigbinary/mail_interceptor/pull/20 updates README.

**Pull request closed without merging**
