### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by Nuzair46**
**Breaking changes**
Requires following versions: 
```rb
ruby (>= '3.0') 
faraday (>= '2.0.1')
```

### CODE REVIEW

**Comment by Nuzair46** [comment]
@yedhink _a please review and merge.
`activesupport` bump was tested on neeto-mail-interceptor

**Comment by yedhink** [comment]
@udai1931 Is this repo being used anymore? I thought we were using https://github.com/bigbinary/neeto-mail-interceptor.

cc: @Nuzair46

**Comment by udai1931** [comment]
@yedhink I just did a global search and found these three occurences only.
https://github.com/bigbinary/bb-academy-web/blob/main/Gemfile#L74
https://github.com/bigbinary/wheel/blob/main/Gemfile#L67
https://github.com/bigbinary/gitemit/blob/main/Gemfile#L69

**Comment by Nuzair46** [comment]
@yedhink @udai1931 neeto uses neeto-mail-interceptor because we have a custom logic to avoid bounced emails. This gem is only used in products that are not part of neeto. Since this gem is being used by other users, I thought of just keeping it upto date to support latest faraday and ruby.

**Pull request merged**
