### PR TITLE
ignore cc and bcc

### PR DESCRIPTION
**Pull request by hooopo**
Custom bcc and cc options.

### CODE REVIEW

**Comment by vipulnsward** [comment]
Thanks @hooopo. Can you add a simple test for this?

**Comment by hooopo** [comment]
@vipulnsward Added.

**Comment by prathamesh-sonpatki** [comment]
Thanks!

**Comment by aleksandrs-ledovskis** [comment]
@prathamesh-sonpatki Could you do a version bump, please?

**Comment by vipulnsward** [comment]
@aleksandrs-ledovskis I cut a new release.

**Comment by aleksandrs-ledovskis** [comment]
Thanks

**Pull request merged**
